name: ali33
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'  # Update SDK constraint

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  flutter_web_plugins:
    sdk: flutter
  flutter_stripe: ^10.1.1
  cupertino_icons: ^1.0.6
  url_strategy: ^0.2.0
  universal_html: ^2.0.8
  shared_preferences: ^2.0.15
  dio: ^5.4.3+1
  proste_bezier_curve: ^2.0.2
  fluttertoast: ^8.1.1
  image_picker: ^0.8.5+3  
  cached_network_image: ^3.2.3
  provider: ^6.1.2
  connectivity_plus: ^5.0.2  
  im_stepper: ^1.0.1+1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  stream_transform: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
