name: ali33
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'  # Update SDK constraint

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_strategy: ^0.2.0
  universal_html: ^2.0.8
  shared_preferences: ^2.0.15
  dio: ^5.4.3+1
  proste_bezier_curve: ^2.0.2
  fluttertoast: ^8.1.1
  image_picker: ^0.8.5+3  # Update to null-safe version
  cached_network_image: ^3.2.3
  provider: ^6.1.2
  connectivity_plus: ^5.0.2  
  im_stepper: ^1.0.1+1
  # google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
# name: ali33
# description: "A new Flutter project."
# publish_to: 'none' 

# version: 1.0.0+1

# environment:
#   sdk: '>=3.3.4 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_web_plugins:
#     sdk: flutter
#   cupertino_icons: ^1.0.6
#   url_strategy: ^0.2.0
#   universal_html: ^2.0.8
#   shared_preferences: ^2.0.15
#   dio: ^5.4.3+1
#   proste_bezier_curve: ^2.0.2
#   fluttertoast: ^8.1.1
#   image_picker: ^1.1.1  # Updated
#   cached_network_image: ^3.2.3  # Updated
#   provider: ^6.1.2
#   connectivity_wrapper: ^1.1.4  # Replaced connectivity_wrapper
#   im_stepper: ^1.0.1+1
#   google_maps_flutter: ^2.6.1  # Updated
#   permission_handler: ^11.3.1
#   geolocator: ^11.0.0
#   geocoding: ^3.0.0
#   flutter_bloc: ^8.1.5
#   bloc_concurrency: ^0.2.5
#   equatable: ^2.0.5
#   stream_transform: ^2.0.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
#   build_runner: ^2.3.2  # Moved to dev_dependencies
#   build_web_compilers: ^4.0.10  # Moved to dev_dependencies

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/
#     - assets/fonts/

#   fonts:
#     - family: Inter
#       fonts:
#         - asset: assets/fonts/Inter/Inter-Black.ttf
#         - asset: assets/fonts/Inter/Inter-Bold.ttf
#         - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
#         - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
#         - asset: assets/fonts/Inter/Inter-Light.ttf
#         - asset: assets/fonts/Inter/Inter-Medium.ttf
#         - asset: assets/fonts/Inter/Inter-Regular.ttf
#         - asset: assets/fonts/Inter/Inter-SemiBold.ttf
#         - asset: assets/fonts/Inter/Inter-Thin.ttf
# # name: ali33
# # description: "A new Flutter project."
# # publish_to: 'none' 

# # version: 1.0.0+1

# # environment:
# #   sdk: '>=3.3.4 <4.0.0'

# # dependencies:
# #   flutter:
# #     sdk: flutter
# #   flutter_web_plugins:
# #     sdk: flutter
# #   cupertino_icons: ^1.0.6
# #   # Thêm các dependencies khác cho web ở đây
# #   url_strategy: ^0.2.0
# #   universal_html: ^2.0.8
# #   build_runner: ^2.3.2
# #   build_web_compilers: ^4.0.10
# #   shared_preferences: ^2.0.15
# #   dio: ^5.4.3+1
# #   proste_bezier_curve: ^2.0.2
# #   fluttertoast: ^8.1.1
# #   image_picker: ^1.1.0
# #   cached_network_image: ^3.2.0
# #   provider: ^6.1.2
# #   connectivity_wrapper: ^1.0.5
# #   im_stepper: ^1.0.1+1

# #   google_maps_flutter: ^2.2.2
# #   permission_handler: ^11.3.1
# #   geolocator: ^11.0.0
# #   geocoding: ^3.0.0

# #   flutter_bloc: ^8.1.5
# #   bloc_concurrency: ^0.2.5
# #   equatable: ^2.0.5
# #   stream_transform: ^2.0.0

# # dev_dependencies:
# #   flutter_test:
# #     sdk: flutter
# #   flutter_lints: ^3.0.0

# # flutter:
# #   uses-material-design: true

# #   assets:
# #     - assets/images/
# #     - assets/fonts/

# #   fonts:
# #     - family: Inter
# #       fonts:
# #         - asset: assets/fonts/Inter/Inter-Black.ttf
# #         - asset: assets/fonts/Inter/Inter-Bold.ttf
# #         - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
# #         - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
# #         - asset: assets/fonts/Inter/Inter-Light.ttf
# #         - asset: assets/fonts/Inter/Inter-Medium.ttf
# #         - asset: assets/fonts/Inter/Inter-Regular.ttf
# #         - asset: assets/fonts/Inter/Inter-SemiBold.ttf
# #         - asset: assets/fonts/Inter/Inter-Thin.ttf