version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Create a separate Dockerfile for backend
    ports:
      - "5000:5000"

  web:
    build:
      context: ./app  # Build from the app directory
      dockerfile: Dockerfile  # Create a Dockerfile for the web app
    ports:
      - "8080:80"
    volumes:
      - ./app:/app

  chrome:
    image: selenium/standalone-chrome:latest
    depends_on:
      - web
    environment:
      - START_XVFB=false  # Don't need Xvfb if running with a desktop
    command: ["google-chrome", "--no-sandbox", "--headless", "--disable-gpu", "--remote-debugging-port=9222", "http://web:80"]  # Access web server in the 'web' container